//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAHW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAHW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCPU.
        /// </summary>
        internal static string CPUInformationCPU {
            get {
                return ResourceManager.GetString("CPUInformationCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCpuClockSpeed.
        /// </summary>
        internal static string CPUInformationCpuClockSpeed {
            get {
                return ResourceManager.GetString("CPUInformationCpuClockSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCpuCoreClockSpeeds.
        /// </summary>
        internal static string CPUInformationCpuCoreClockSpeeds {
            get {
                return ResourceManager.GetString("CPUInformationCpuCoreClockSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCPUCores.
        /// </summary>
        internal static string CPUInformationCPUCores {
            get {
                return ResourceManager.GetString("CPUInformationCPUCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCpuCoreTemperatures.
        /// </summary>
        internal static string CPUInformationCpuCoreTemperatures {
            get {
                return ResourceManager.GetString("CPUInformationCpuCoreTemperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCPUCoreWorkloads.
        /// </summary>
        internal static string CPUInformationCPUCoreWorkloads {
            get {
                return ResourceManager.GetString("CPUInformationCPUCoreWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCpuTemperature.
        /// </summary>
        internal static string CPUInformationCpuTemperature {
            get {
                return ResourceManager.GetString("CPUInformationCpuTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationCPUTotalWorkload.
        /// </summary>
        internal static string CPUInformationCPUTotalWorkload {
            get {
                return ResourceManager.GetString("CPUInformationCPUTotalWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationMaxAppreviation.
        /// </summary>
        internal static string CPUInformationMaxAppreviation {
            get {
                return ResourceManager.GetString("CPUInformationMaxAppreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationMinAppreviation.
        /// </summary>
        internal static string CPUInformationMinAppreviation {
            get {
                return ResourceManager.GetString("CPUInformationMinAppreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationPercentUsage.
        /// </summary>
        internal static string CPUInformationPercentUsage {
            get {
                return ResourceManager.GetString("CPUInformationPercentUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CPUInformationPowerConsumption.
        /// </summary>
        internal static string CPUInformationPowerConsumption {
            get {
                return ResourceManager.GetString("CPUInformationPowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationCurrentHorizontalResolution.
        /// </summary>
        internal static string GPUInformationCurrentHorizontalResolution {
            get {
                return ResourceManager.GetString("GPUInformationCurrentHorizontalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationCurrentRefreshRate.
        /// </summary>
        internal static string GPUInformationCurrentRefreshRate {
            get {
                return ResourceManager.GetString("GPUInformationCurrentRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationCurrentVerticalResolution.
        /// </summary>
        internal static string GPUInformationCurrentVerticalResolution {
            get {
                return ResourceManager.GetString("GPUInformationCurrentVerticalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationDriverVersion.
        /// </summary>
        internal static string GPUInformationDriverVersion {
            get {
                return ResourceManager.GetString("GPUInformationDriverVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationName.
        /// </summary>
        internal static string GPUInformationName {
            get {
                return ResourceManager.GetString("GPUInformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationVideoMode.
        /// </summary>
        internal static string GPUInformationVideoMode {
            get {
                return ResourceManager.GetString("GPUInformationVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GPUInformationVideoProcessor.
        /// </summary>
        internal static string GPUInformationVideoProcessor {
            get {
                return ResourceManager.GetString("GPUInformationVideoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HDDInformationSmartCurrentValue.
        /// </summary>
        internal static string HDDInformationSmartCurrentValue {
            get {
                return ResourceManager.GetString("HDDInformationSmartCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HDDInformationSMARTInformation.
        /// </summary>
        internal static string HDDInformationSMARTInformation {
            get {
                return ResourceManager.GetString("HDDInformationSMARTInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HDDInformationSmartParameter.
        /// </summary>
        internal static string HDDInformationSmartParameter {
            get {
                return ResourceManager.GetString("HDDInformationSmartParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HDDInformationSmartThreshold.
        /// </summary>
        internal static string HDDInformationSmartThreshold {
            get {
                return ResourceManager.GetString("HDDInformationSmartThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HDDInformationSmartWorstValue.
        /// </summary>
        internal static string HDDInformationSmartWorstValue {
            get {
                return ResourceManager.GetString("HDDInformationSmartWorstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformation3VCC.
        /// </summary>
        internal static string MainboardInformation3VCC {
            get {
                return ResourceManager.GetString("MainboardInformation3VCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformation3VSB.
        /// </summary>
        internal static string MainboardInformation3VSB {
            get {
                return ResourceManager.GetString("MainboardInformation3VSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationAVCC.
        /// </summary>
        internal static string MainboardInformationAVCC {
            get {
                return ResourceManager.GetString("MainboardInformationAVCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationCPUVcore.
        /// </summary>
        internal static string MainboardInformationCPUVcore {
            get {
                return ResourceManager.GetString("MainboardInformationCPUVcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationMainboardInfo.
        /// </summary>
        internal static string MainboardInformationMainboardInfo {
            get {
                return ResourceManager.GetString("MainboardInformationMainboardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationVBAT.
        /// </summary>
        internal static string MainboardInformationVBAT {
            get {
                return ResourceManager.GetString("MainboardInformationVBAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationVoltagesHeader.
        /// </summary>
        internal static string MainboardInformationVoltagesHeader {
            get {
                return ResourceManager.GetString("MainboardInformationVoltagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainboardInformationVTT.
        /// </summary>
        internal static string MainboardInformationVTT {
            get {
                return ResourceManager.GetString("MainboardInformationVTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowAbout.
        /// </summary>
        internal static string MainWindowAbout {
            get {
                return ResourceManager.GetString("MainWindowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowCPU.
        /// </summary>
        internal static string MainWindowCPU {
            get {
                return ResourceManager.GetString("MainWindowCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowCPUCoreTemperatures.
        /// </summary>
        internal static string MainWindowCPUCoreTemperatures {
            get {
                return ResourceManager.GetString("MainWindowCPUCoreTemperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowCPUCoreWorkload.
        /// </summary>
        internal static string MainWindowCPUCoreWorkload {
            get {
                return ResourceManager.GetString("MainWindowCPUCoreWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowCPUInformation.
        /// </summary>
        internal static string MainWindowCPUInformation {
            get {
                return ResourceManager.GetString("MainWindowCPUInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowFAN.
        /// </summary>
        internal static string MainWindowFAN {
            get {
                return ResourceManager.GetString("MainWindowFAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowFanControl.
        /// </summary>
        internal static string MainWindowFanControl {
            get {
                return ResourceManager.GetString("MainWindowFanControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowGPU.
        /// </summary>
        internal static string MainWindowGPU {
            get {
                return ResourceManager.GetString("MainWindowGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowGPUInformation.
        /// </summary>
        internal static string MainWindowGPUInformation {
            get {
                return ResourceManager.GetString("MainWindowGPUInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowHDD.
        /// </summary>
        internal static string MainWindowHDD {
            get {
                return ResourceManager.GetString("MainWindowHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowHDDInformation.
        /// </summary>
        internal static string MainWindowHDDInformation {
            get {
                return ResourceManager.GetString("MainWindowHDDInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowHelp.
        /// </summary>
        internal static string MainWindowHelp {
            get {
                return ResourceManager.GetString("MainWindowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowHint.
        /// </summary>
        internal static string MainWindowHint {
            get {
                return ResourceManager.GetString("MainWindowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowHome.
        /// </summary>
        internal static string MainWindowHome {
            get {
                return ResourceManager.GetString("MainWindowHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowMainboard.
        /// </summary>
        internal static string MainWindowMainboard {
            get {
                return ResourceManager.GetString("MainWindowMainboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowMainboardInformation.
        /// </summary>
        internal static string MainWindowMainboardInformation {
            get {
                return ResourceManager.GetString("MainWindowMainboardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowOverview.
        /// </summary>
        internal static string MainWindowOverview {
            get {
                return ResourceManager.GetString("MainWindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowRAM.
        /// </summary>
        internal static string MainWindowRAM {
            get {
                return ResourceManager.GetString("MainWindowRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowRAMInformation.
        /// </summary>
        internal static string MainWindowRAMInformation {
            get {
                return ResourceManager.GetString("MainWindowRAMInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowSettings.
        /// </summary>
        internal static string MainWindowSettings {
            get {
                return ResourceManager.GetString("MainWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowSystemInformation.
        /// </summary>
        internal static string MainWindowSystemInformation {
            get {
                return ResourceManager.GetString("MainWindowSystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MainWindowWelcome.
        /// </summary>
        internal static string MainWindowWelcome {
            get {
                return ResourceManager.GetString("MainWindowWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PageAboutText.
        /// </summary>
        internal static string PageAboutText {
            get {
                return ResourceManager.GetString("PageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationHeader.
        /// </summary>
        internal static string RAMInformationHeader {
            get {
                return ResourceManager.GetString("RAMInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderBankLabel.
        /// </summary>
        internal static string RAMInformationListViewHeaderBankLabel {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderBankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderCapacity.
        /// </summary>
        internal static string RAMInformationListViewHeaderCapacity {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderChannel.
        /// </summary>
        internal static string RAMInformationListViewHeaderChannel {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderFormFactor.
        /// </summary>
        internal static string RAMInformationListViewHeaderFormFactor {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderFormFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderPartNumber.
        /// </summary>
        internal static string RAMInformationListViewHeaderPartNumber {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RAMInformationListViewHeaderSpeed.
        /// </summary>
        internal static string RAMInformationListViewHeaderSpeed {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlCPUInformationCores.
        /// </summary>
        internal static string UserControlCPUInformationCores {
            get {
                return ResourceManager.GetString("UserControlCPUInformationCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlCPUInformationHeader.
        /// </summary>
        internal static string UserControlCPUInformationHeader {
            get {
                return ResourceManager.GetString("UserControlCPUInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlCPUInformationLogicalProcessors.
        /// </summary>
        internal static string UserControlCPUInformationLogicalProcessors {
            get {
                return ResourceManager.GetString("UserControlCPUInformationLogicalProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlCPUInformationManufacturer.
        /// </summary>
        internal static string UserControlCPUInformationManufacturer {
            get {
                return ResourceManager.GetString("UserControlCPUInformationManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlCPUInformationProduct.
        /// </summary>
        internal static string UserControlCPUInformationProduct {
            get {
                return ResourceManager.GetString("UserControlCPUInformationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlFanContolMaxValue.
        /// </summary>
        internal static string UserControlFanContolMaxValue {
            get {
                return ResourceManager.GetString("UserControlFanContolMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlFanContolMinValue.
        /// </summary>
        internal static string UserControlFanContolMinValue {
            get {
                return ResourceManager.GetString("UserControlFanContolMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlFanContolValue.
        /// </summary>
        internal static string UserControlFanContolValue {
            get {
                return ResourceManager.GetString("UserControlFanContolValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlGPUInformationHeader.
        /// </summary>
        internal static string UserControlGPUInformationHeader {
            get {
                return ResourceManager.GetString("UserControlGPUInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardInformationHeader.
        /// </summary>
        internal static string UserControlMainboardInformationHeader {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardInformationIOHardware.
        /// </summary>
        internal static string UserControlMainboardInformationIOHardware {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationIOHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardInformationManufacturer.
        /// </summary>
        internal static string UserControlMainboardInformationManufacturer {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardInformationProduct.
        /// </summary>
        internal static string UserControlMainboardInformationProduct {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardInformationSerialNumber.
        /// </summary>
        internal static string UserControlMainboardInformationSerialNumber {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserControlMainboardTemperatureSensorsHeader.
        /// </summary>
        internal static string UserControlMainboardTemperatureSensorsHeader {
            get {
                return ResourceManager.GetString("UserControlMainboardTemperatureSensorsHeader", resourceCulture);
            }
        }
    }
}
