//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAHW.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAHW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AppearancePageFontSize ähnelt.
        /// </summary>
        internal static string AppearancePageFontSize {
            get {
                return ResourceManager.GetString("AppearancePageFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AppearancePageLanguage ähnelt.
        /// </summary>
        internal static string AppearancePageLanguage {
            get {
                return ResourceManager.GetString("AppearancePageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AppearancePageTheme ähnelt.
        /// </summary>
        internal static string AppearancePageTheme {
            get {
                return ResourceManager.GetString("AppearancePageTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AppearancePageTitle ähnelt.
        /// </summary>
        internal static string AppearancePageTitle {
            get {
                return ResourceManager.GetString("AppearancePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AutoRunsLogon ähnelt.
        /// </summary>
        internal static string AutoRunsLogon {
            get {
                return ResourceManager.GetString("AutoRunsLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCPU ähnelt.
        /// </summary>
        internal static string CPUInformationCPU {
            get {
                return ResourceManager.GetString("CPUInformationCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCpuClockSpeed ähnelt.
        /// </summary>
        internal static string CPUInformationCpuClockSpeed {
            get {
                return ResourceManager.GetString("CPUInformationCpuClockSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCpuCoreClockSpeeds ähnelt.
        /// </summary>
        internal static string CPUInformationCpuCoreClockSpeeds {
            get {
                return ResourceManager.GetString("CPUInformationCpuCoreClockSpeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCPUCores ähnelt.
        /// </summary>
        internal static string CPUInformationCPUCores {
            get {
                return ResourceManager.GetString("CPUInformationCPUCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCpuCoreTemperatures ähnelt.
        /// </summary>
        internal static string CPUInformationCpuCoreTemperatures {
            get {
                return ResourceManager.GetString("CPUInformationCpuCoreTemperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCPUCoreWorkloads ähnelt.
        /// </summary>
        internal static string CPUInformationCPUCoreWorkloads {
            get {
                return ResourceManager.GetString("CPUInformationCPUCoreWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCpuTemperature ähnelt.
        /// </summary>
        internal static string CPUInformationCpuTemperature {
            get {
                return ResourceManager.GetString("CPUInformationCpuTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationCPUTotalWorkload ähnelt.
        /// </summary>
        internal static string CPUInformationCPUTotalWorkload {
            get {
                return ResourceManager.GetString("CPUInformationCPUTotalWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationMaxAppreviation ähnelt.
        /// </summary>
        internal static string CPUInformationMaxAppreviation {
            get {
                return ResourceManager.GetString("CPUInformationMaxAppreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationMinAppreviation ähnelt.
        /// </summary>
        internal static string CPUInformationMinAppreviation {
            get {
                return ResourceManager.GetString("CPUInformationMinAppreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationPercentUsage ähnelt.
        /// </summary>
        internal static string CPUInformationPercentUsage {
            get {
                return ResourceManager.GetString("CPUInformationPercentUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @CPUInformationPowerConsumption ähnelt.
        /// </summary>
        internal static string CPUInformationPowerConsumption {
            get {
                return ResourceManager.GetString("CPUInformationPowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DirectoriesPageTitle ähnelt.
        /// </summary>
        internal static string DirectoriesPageTitle {
            get {
                return ResourceManager.GetString("DirectoriesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationCurrentHorizontalResolution ähnelt.
        /// </summary>
        internal static string GPUInformationCurrentHorizontalResolution {
            get {
                return ResourceManager.GetString("GPUInformationCurrentHorizontalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationCurrentRefreshRate ähnelt.
        /// </summary>
        internal static string GPUInformationCurrentRefreshRate {
            get {
                return ResourceManager.GetString("GPUInformationCurrentRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationCurrentVerticalResolution ähnelt.
        /// </summary>
        internal static string GPUInformationCurrentVerticalResolution {
            get {
                return ResourceManager.GetString("GPUInformationCurrentVerticalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationDriverVersion ähnelt.
        /// </summary>
        internal static string GPUInformationDriverVersion {
            get {
                return ResourceManager.GetString("GPUInformationDriverVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationName ähnelt.
        /// </summary>
        internal static string GPUInformationName {
            get {
                return ResourceManager.GetString("GPUInformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationVideoMode ähnelt.
        /// </summary>
        internal static string GPUInformationVideoMode {
            get {
                return ResourceManager.GetString("GPUInformationVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @GPUInformationVideoProcessor ähnelt.
        /// </summary>
        internal static string GPUInformationVideoProcessor {
            get {
                return ResourceManager.GetString("GPUInformationVideoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationFreeSpace ähnelt.
        /// </summary>
        internal static string HDDInformationFreeSpace {
            get {
                return ResourceManager.GetString("HDDInformationFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationPartitions ähnelt.
        /// </summary>
        internal static string HDDInformationPartitions {
            get {
                return ResourceManager.GetString("HDDInformationPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationSmartCurrentValue ähnelt.
        /// </summary>
        internal static string HDDInformationSmartCurrentValue {
            get {
                return ResourceManager.GetString("HDDInformationSmartCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationSMARTInformation ähnelt.
        /// </summary>
        internal static string HDDInformationSMARTInformation {
            get {
                return ResourceManager.GetString("HDDInformationSMARTInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationSmartParameter ähnelt.
        /// </summary>
        internal static string HDDInformationSmartParameter {
            get {
                return ResourceManager.GetString("HDDInformationSmartParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationSmartThreshold ähnelt.
        /// </summary>
        internal static string HDDInformationSmartThreshold {
            get {
                return ResourceManager.GetString("HDDInformationSmartThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationSmartWorstValue ähnelt.
        /// </summary>
        internal static string HDDInformationSmartWorstValue {
            get {
                return ResourceManager.GetString("HDDInformationSmartWorstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationTitle ähnelt.
        /// </summary>
        internal static string HDDInformationTitle {
            get {
                return ResourceManager.GetString("HDDInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationTotalSpace ähnelt.
        /// </summary>
        internal static string HDDInformationTotalSpace {
            get {
                return ResourceManager.GetString("HDDInformationTotalSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @HDDInformationUsedSpace ähnelt.
        /// </summary>
        internal static string HDDInformationUsedSpace {
            get {
                return ResourceManager.GetString("HDDInformationUsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlActualValueAnnotation ähnelt.
        /// </summary>
        internal static string MainboardFanControlActualValueAnnotation {
            get {
                return ResourceManager.GetString("MainboardFanControlActualValueAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlDialogDisabledText ähnelt.
        /// </summary>
        internal static string MainboardFanControlDialogDisabledText {
            get {
                return ResourceManager.GetString("MainboardFanControlDialogDisabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlErrorCreatingConfig ähnelt.
        /// </summary>
        internal static string MainboardFanControlErrorCreatingConfigFile {
            get {
                return ResourceManager.GetString("MainboardFanControlErrorCreatingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlErrorReadingConfig ähnelt.
        /// </summary>
        internal static string MainboardFanControlErrorReadingConfigFile {
            get {
                return ResourceManager.GetString("MainboardFanControlErrorReadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlErrorReadingFanControllerTemplates ähnelt.
        /// </summary>
        internal static string MainboardFanControlErrorReadingFanControllerTemplates {
            get {
                return ResourceManager.GetString("MainboardFanControlErrorReadingFanControllerTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlErrorSettingFanSpeed ähnelt.
        /// </summary>
        internal static string MainboardFanControlErrorSettingFanSpeed {
            get {
                return ResourceManager.GetString("MainboardFanControlErrorSettingFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlErrorWritingConfigFile ähnelt.
        /// </summary>
        internal static string MainboardFanControlErrorWritingConfigFile {
            get {
                return ResourceManager.GetString("MainboardFanControlErrorWritingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardFanControlNote ähnelt.
        /// </summary>
        internal static string MainboardFanControlNote {
            get {
                return ResourceManager.GetString("MainboardFanControlNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformation3VCC ähnelt.
        /// </summary>
        internal static string MainboardInformation3VCC {
            get {
                return ResourceManager.GetString("MainboardInformation3VCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformation3VSB ähnelt.
        /// </summary>
        internal static string MainboardInformation3VSB {
            get {
                return ResourceManager.GetString("MainboardInformation3VSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationAVCC ähnelt.
        /// </summary>
        internal static string MainboardInformationAVCC {
            get {
                return ResourceManager.GetString("MainboardInformationAVCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationCPUVcore ähnelt.
        /// </summary>
        internal static string MainboardInformationCPUVcore {
            get {
                return ResourceManager.GetString("MainboardInformationCPUVcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationMainboardInfo ähnelt.
        /// </summary>
        internal static string MainboardInformationMainboardInfo {
            get {
                return ResourceManager.GetString("MainboardInformationMainboardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationVBAT ähnelt.
        /// </summary>
        internal static string MainboardInformationVBAT {
            get {
                return ResourceManager.GetString("MainboardInformationVBAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationVoltagesHeader ähnelt.
        /// </summary>
        internal static string MainboardInformationVoltagesHeader {
            get {
                return ResourceManager.GetString("MainboardInformationVoltagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainboardInformationVTT ähnelt.
        /// </summary>
        internal static string MainboardInformationVTT {
            get {
                return ResourceManager.GetString("MainboardInformationVTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowAbout ähnelt.
        /// </summary>
        internal static string MainWindowAbout {
            get {
                return ResourceManager.GetString("MainWindowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowAutoRuns ähnelt.
        /// </summary>
        internal static string MainWindowAutoRuns {
            get {
                return ResourceManager.GetString("MainWindowAutoRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowCPU ähnelt.
        /// </summary>
        internal static string MainWindowCPU {
            get {
                return ResourceManager.GetString("MainWindowCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowCPUCoreTemperatures ähnelt.
        /// </summary>
        internal static string MainWindowCPUCoreTemperatures {
            get {
                return ResourceManager.GetString("MainWindowCPUCoreTemperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowCPUCoreWorkload ähnelt.
        /// </summary>
        internal static string MainWindowCPUCoreWorkload {
            get {
                return ResourceManager.GetString("MainWindowCPUCoreWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowCPUInformation ähnelt.
        /// </summary>
        internal static string MainWindowCPUInformation {
            get {
                return ResourceManager.GetString("MainWindowCPUInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowFAN ähnelt.
        /// </summary>
        internal static string MainWindowFAN {
            get {
                return ResourceManager.GetString("MainWindowFAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowFanControl ähnelt.
        /// </summary>
        internal static string MainWindowFanControl {
            get {
                return ResourceManager.GetString("MainWindowFanControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowGPU ähnelt.
        /// </summary>
        internal static string MainWindowGPU {
            get {
                return ResourceManager.GetString("MainWindowGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowGPUInformation ähnelt.
        /// </summary>
        internal static string MainWindowGPUInformation {
            get {
                return ResourceManager.GetString("MainWindowGPUInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowHDD ähnelt.
        /// </summary>
        internal static string MainWindowHDD {
            get {
                return ResourceManager.GetString("MainWindowHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowHDDInformation ähnelt.
        /// </summary>
        internal static string MainWindowHDDInformation {
            get {
                return ResourceManager.GetString("MainWindowHDDInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowHelp ähnelt.
        /// </summary>
        internal static string MainWindowHelp {
            get {
                return ResourceManager.GetString("MainWindowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowHint ähnelt.
        /// </summary>
        internal static string MainWindowHint {
            get {
                return ResourceManager.GetString("MainWindowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowHome ähnelt.
        /// </summary>
        internal static string MainWindowHome {
            get {
                return ResourceManager.GetString("MainWindowHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowMainboard ähnelt.
        /// </summary>
        internal static string MainWindowMainboard {
            get {
                return ResourceManager.GetString("MainWindowMainboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowMainboardInformation ähnelt.
        /// </summary>
        internal static string MainWindowMainboardInformation {
            get {
                return ResourceManager.GetString("MainWindowMainboardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowOverview ähnelt.
        /// </summary>
        internal static string MainWindowOverview {
            get {
                return ResourceManager.GetString("MainWindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowRAM ähnelt.
        /// </summary>
        internal static string MainWindowRAM {
            get {
                return ResourceManager.GetString("MainWindowRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowRAMInformation ähnelt.
        /// </summary>
        internal static string MainWindowRAMInformation {
            get {
                return ResourceManager.GetString("MainWindowRAMInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowServiceManagement ähnelt.
        /// </summary>
        internal static string MainWindowServiceManagement {
            get {
                return ResourceManager.GetString("MainWindowServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowSettings ähnelt.
        /// </summary>
        internal static string MainWindowSettings {
            get {
                return ResourceManager.GetString("MainWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowSystemInformation ähnelt.
        /// </summary>
        internal static string MainWindowSystemInformation {
            get {
                return ResourceManager.GetString("MainWindowSystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowTaskbarContextMenuClose ähnelt.
        /// </summary>
        internal static string MainWindowTaskbarContextMenuClose {
            get {
                return ResourceManager.GetString("MainWindowTaskbarContextMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowTitle ähnelt.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @MainWindowWelcome ähnelt.
        /// </summary>
        internal static string MainWindowWelcome {
            get {
                return ResourceManager.GetString("MainWindowWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @PageAboutText ähnelt.
        /// </summary>
        internal static string PageAboutText {
            get {
                return ResourceManager.GetString("PageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationHeader ähnelt.
        /// </summary>
        internal static string RAMInformationHeader {
            get {
                return ResourceManager.GetString("RAMInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderBankLabel ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderBankLabel {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderBankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderCapacity ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderCapacity {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderChannel ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderChannel {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderFormFactor ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderFormFactor {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderFormFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderPartNumber ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderPartNumber {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @RAMInformationListViewHeaderSpeed ähnelt.
        /// </summary>
        internal static string RAMInformationListViewHeaderSpeed {
            get {
                return ResourceManager.GetString("RAMInformationListViewHeaderSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ServiceManagementTitle ähnelt.
        /// </summary>
        internal static string ServiceManagementTitle {
            get {
                return ResourceManager.GetString("ServiceManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @SettingsPageAbout ähnelt.
        /// </summary>
        internal static string SettingsPageAbout {
            get {
                return ResourceManager.GetString("SettingsPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @SettingsPageAppearance ähnelt.
        /// </summary>
        internal static string SettingsPageAppearance {
            get {
                return ResourceManager.GetString("SettingsPageAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @SettingsPageDirectories ähnelt.
        /// </summary>
        internal static string SettingsPageDirectories {
            get {
                return ResourceManager.GetString("SettingsPageDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @SettingsPageLicense ähnelt.
        /// </summary>
        internal static string SettingsPageLicense {
            get {
                return ResourceManager.GetString("SettingsPageLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlCPUInformationCores ähnelt.
        /// </summary>
        internal static string UserControlCPUInformationCores {
            get {
                return ResourceManager.GetString("UserControlCPUInformationCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlCPUInformationHeader ähnelt.
        /// </summary>
        internal static string UserControlCPUInformationHeader {
            get {
                return ResourceManager.GetString("UserControlCPUInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlCPUInformationLogicalProcessors ähnelt.
        /// </summary>
        internal static string UserControlCPUInformationLogicalProcessors {
            get {
                return ResourceManager.GetString("UserControlCPUInformationLogicalProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlCPUInformationManufacturer ähnelt.
        /// </summary>
        internal static string UserControlCPUInformationManufacturer {
            get {
                return ResourceManager.GetString("UserControlCPUInformationManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlCPUInformationProduct ähnelt.
        /// </summary>
        internal static string UserControlCPUInformationProduct {
            get {
                return ResourceManager.GetString("UserControlCPUInformationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolAdvancedMode ähnelt.
        /// </summary>
        internal static string UserControlFanContolAdvancedMode {
            get {
                return ResourceManager.GetString("UserControlFanContolAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolDefaultMode ähnelt.
        /// </summary>
        internal static string UserControlFanContolDefaultMode {
            get {
                return ResourceManager.GetString("UserControlFanContolDefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolMaxValue ähnelt.
        /// </summary>
        internal static string UserControlFanContolMaxValue {
            get {
                return ResourceManager.GetString("UserControlFanContolMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolMinValue ähnelt.
        /// </summary>
        internal static string UserControlFanContolMinValue {
            get {
                return ResourceManager.GetString("UserControlFanContolMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolSettings ähnelt.
        /// </summary>
        internal static string UserControlFanContolSettings {
            get {
                return ResourceManager.GetString("UserControlFanContolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolTemperatureSensor ähnelt.
        /// </summary>
        internal static string UserControlFanContolTemperatureSensor {
            get {
                return ResourceManager.GetString("UserControlFanContolTemperatureSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanContolValue ähnelt.
        /// </summary>
        internal static string UserControlFanContolValue {
            get {
                return ResourceManager.GetString("UserControlFanContolValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanFanVoltageInPercent ähnelt.
        /// </summary>
        internal static string UserControlFanFanVoltageInPercent {
            get {
                return ResourceManager.GetString("UserControlFanFanVoltageInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlFanTemperatureSensorValue ähnelt.
        /// </summary>
        internal static string UserControlFanTemperatureSensorValue {
            get {
                return ResourceManager.GetString("UserControlFanTemperatureSensorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlGPUInformationHeader ähnelt.
        /// </summary>
        internal static string UserControlGPUInformationHeader {
            get {
                return ResourceManager.GetString("UserControlGPUInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardInformationHeader ähnelt.
        /// </summary>
        internal static string UserControlMainboardInformationHeader {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardInformationIOHardware ähnelt.
        /// </summary>
        internal static string UserControlMainboardInformationIOHardware {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationIOHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardInformationManufacturer ähnelt.
        /// </summary>
        internal static string UserControlMainboardInformationManufacturer {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardInformationProduct ähnelt.
        /// </summary>
        internal static string UserControlMainboardInformationProduct {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardInformationSerialNumber ähnelt.
        /// </summary>
        internal static string UserControlMainboardInformationSerialNumber {
            get {
                return ResourceManager.GetString("UserControlMainboardInformationSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @UserControlMainboardTemperatureSensorsHeader ähnelt.
        /// </summary>
        internal static string UserControlMainboardTemperatureSensorsHeader {
            get {
                return ResourceManager.GetString("UserControlMainboardTemperatureSensorsHeader", resourceCulture);
            }
        }
    }
}
